###
GET http://localhost:3000/books
###
POST  http://localhost:3000/books
Accept: application/json
Content-Type: application/json

{
    "title": "titlealdkjalekdj",
    "author": "uathoraskd",
    "category": "catgoeryalsdk"
}
###
PUT  http://localhost:3000/books/4fde0491-a881-4944-9636-d15906f9923f
Accept: application/json
Content-Type: application/json

{
    "title": "title edited",
    "author": "author edited",
    "category": "catgoery edited"
}
###
DELETE  http://localhost:3000/books/e8b2f466-330c-4832-b00e-00e2beef8afe

### 
GET http://localhost:3000/users

###
GET http://localhost:3000/users/e0f29a08-f574-495b-a444-72dc5329af51
###
POST  http://localhost:3000/users
Content-Type: application/json

{
    "email": "malikmal98@gmail.com",
    "age": 29
}
###
PATCH  http://localhost:3000/users/e0f29a08-f574-495b-a444-72dc5329af51
Content-Type: application/json

{
    "age": 21
}