###
GET http://localhost:3000
###
GET http://localhost:3000/todo
###
GET http://localhost:3000/todo/asd
###
POST http://localhost:3000/todo
Content-Type: application/json

{
    "name": "contoh"
}
###
PUT http://localhost:3000/todo/8r7mz
Content-Type: application/json

{
    "name": "contoh edited"
}
###
DELETE http://localhost:3000/todo/8r7mz
